# This is a basic workflow to help you get started with Actions

name: NpmPublish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the refactor branch
on:
  push:
    branches: [ refactor, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
